services:
  - type: web
    name: srm-student-hub
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
