services:
  - type: web
    name: srm-student-hub
    env: python
    plan: free
    buildCommand: export PLAYWRIGHT_BROWSERS_PATH=/opt/render/project/src/.playwright && pip install -r requirements.txt && playwright install chromium
    startCommand: export PLAYWRIGHT_BROWSERS_PATH=/opt/render/project/src/.playwright && gunicorn server:app --bind 0.0.0.0:$PORT --timeout 300
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
